MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN3D"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN-NL"
    FREEZE_CONV_BODY_AT: 2 # If trained from scratch, there should be no frozen layers
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True # CHANGED FROM True
    SCORE_THRESH: 0.001
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 4
#  STEPS: (66375, 81125)  # 9th and 11th epoch (118k imgs / 16img/batch = 7375 iter/epoch)
#  MAX_ITER: 88500
#  STEPS: (132750, 162250)  # 9th and 11th epoch (118k imgs / 8img/batch = 14750 iter/epoch)
#  MAX_ITER: 177000
#TEST:
#  IMS_PER_BATCH: 2

NON_LOCAL_CTX:
  ENABLED: False  # Enable 4D computation
  MODULE: "SimplifiedNL"
  FIRST_CTX_FRAME: 0  # 0 includes current frame, 1 to start from previous frame TODO DELETE (defaults.py = 1)
  RETURN_ATTENTION: False
  STAGES: (4,)  # Index of Resnet blocks where non-local modules are inserted

OUTPUT_DIR: '/home/jorge/4tb/model_zoo/maskrcnn-benchmark/R-50-MASK-FPN-Hawaii'