MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN3D"
#  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: '/home/jorge/4tb/model_zoo/maskrcnn-benchmark/R-50-FPN-NL-Alaska/model_final.pth'
  BACKBONE:
    CONV_BODY: "R-50-FPN-NL"
    FREEZE_CONV_BODY_AT: 2 # If trained from scratch, there should be no frozen layers
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
#  RPN_ONLY: True
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True # CHANGED FROM True
    SCORE_THRESH: 0.001
  ROI_BOX_HEAD:
    NUM_CLASSES: 4
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("kitti_nl_train_crowd",)
  TEST: ("kitti_nl_val_crowd",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.00125 # 0.00125
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1
  STEPS: ()
  MAX_ITER: 180000
#  WARMUP_ITERS: 500
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 10000
TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
    H_FLIP: True
    SCALES: (375, 500)
    MAX_SIZE: 2000
    SCALE_H_FLIP: True

# Size of the smallest side of the image during training
INPUT:
  MIN_SIZE_TRAIN: (375, 500, )  # 375, 500 (800,)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 500
  MAX_SIZE_TEST: 2000
#  PIXEL_MEAN: [93.5878, 97.8160, 92.8664] # KITTI
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True

NON_LOCAL:
  ENABLED: True  # Enable 4D computation
#  FIRST_CTX_FRAME: 0  # 0 includes current frame, 1 to start from previous frame TODO DELETE (defaults.py = 1)
  RETURN_ATTENTION: False
  AT_BLOCKS: (4,)  # Index of Resnet blocks where non-local modules are inserted
  PATCH_SIZE: 7
  USE_BN: False

OUTPUT_DIR: '/home/jorge/4tb/model_zoo/maskrcnn-benchmark/R-50-FPN-NL-Alaska'